// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { ApproveCycleDraftData, ApproveCycleDraftErrors, ApproveCycleDraftResponses, ArchiveChildData, ArchiveChildErrors, ArchiveChildResponses, BootstrapFamilyData, BootstrapFamilyErrors, BootstrapFamilyResponses, CreateChildData, CreateChildErrors, CreateChildResponses, CreateCycleData, CreateCycleErrors, CreateCycleResponses, CreateSubjectData, CreateSubjectErrors, CreateSubjectResponses, CreateSubmissionData, CreateSubmissionErrors, CreateSubmissionResponses, GenerateAssessmentData, GenerateAssessmentErrors, GenerateAssessmentForCycleData, GenerateAssessmentForCycleErrors, GenerateAssessmentForCycleResponses, GenerateAssessmentResponses, GenerateGapReportData, GenerateGapReportErrors, GenerateGapReportResponses, GetCaptureViewData, GetCaptureViewErrors, GetCaptureViewResponses, GetCycleData, GetCycleErrors, GetCycleResponses, GetGapReportData, GetGapReportErrors, GetGapReportResponses, GetHealthData, GetHealthResponses, GradeSubmissionMarksData, GradeSubmissionMarksErrors, GradeSubmissionMarksResponses, ListChildrenData, ListChildrenResponses, ListCyclesData, ListCyclesResponses, ListFamiliesData, ListFamiliesResponses, ListQuestionMarksData, ListQuestionMarksErrors, ListQuestionMarksResponses, ListSubjectsData, ListSubjectsResponses, PublishMarksData, PublishMarksErrors, PublishMarksResponses, ReviewQuestionMarkData, ReviewQuestionMarkErrors, ReviewQuestionMarkResponses, UpdateChildData, UpdateChildErrors, UpdateChildResponses, ValidateAssessmentData, ValidateAssessmentErrors, ValidateAssessmentResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Get Health
 */
export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>): RequestResult<GetHealthResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetHealthResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Validate
 *
 * Validate a raw assessment payload against the canonical schema.
 *
 * Always returns HTTP 200 — the validation outcome (valid or not) is the
 * payload, not an HTTP error.
 */
export const validateAssessment = <ThrowOnError extends boolean = false>(options: Options<ValidateAssessmentData, ThrowOnError>): RequestResult<ValidateAssessmentResponses, ValidateAssessmentErrors, ThrowOnError> => (options.client ?? client).post<ValidateAssessmentResponses, ValidateAssessmentErrors, ThrowOnError>({
    url: '/assessments/validate',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Generate
 *
 * Generate a schema-valid Variant-A assessment from a scope text.
 *
 * - Requires a valid caller identity (``X-User-Id`` header in PR-1).
 * - Routes output through the single validation gate.
 * - On success, persists to Postgres under the caller's family tenancy.
 * - On validation failure after one repair retry, returns a structured error
 * (HTTP 422 with issues list).
 */
export const generateAssessment = <ThrowOnError extends boolean = false>(options: Options<GenerateAssessmentData, ThrowOnError>): RequestResult<GenerateAssessmentResponses, GenerateAssessmentErrors, ThrowOnError> => (options.client ?? client).post<GenerateAssessmentResponses, GenerateAssessmentErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'x-user-id', type: 'apiKey' }],
    url: '/assessments/generate',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List the families the caller belongs to.
 */
export const listFamilies = <ThrowOnError extends boolean = false>(options?: Options<ListFamiliesData, ThrowOnError>): RequestResult<ListFamiliesResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListFamiliesResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'x-user-id', type: 'apiKey' }],
    url: '/families',
    ...options
});

/**
 * Bootstrap: create a family + membership (+ optional first child).
 *
 * Create the caller's family in a single atomic DB call via the
 * SECURITY DEFINER function (0003_bootstrap.sql).
 *
 * Idempotent: if the caller already has a family, returns it unchanged.
 * ``child_name`` and ``grade_label`` must both be provided or both omitted.
 */
export const bootstrapFamily = <ThrowOnError extends boolean = false>(options: Options<BootstrapFamilyData, ThrowOnError>): RequestResult<BootstrapFamilyResponses, BootstrapFamilyErrors, ThrowOnError> => (options.client ?? client).post<BootstrapFamilyResponses, BootstrapFamilyErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'x-user-id', type: 'apiKey' }],
    url: '/families',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List children in the caller's family.
 */
export const listChildren = <ThrowOnError extends boolean = false>(options?: Options<ListChildrenData, ThrowOnError>): RequestResult<ListChildrenResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListChildrenResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'x-user-id', type: 'apiKey' }],
    url: '/children',
    ...options
});

/**
 * Add a child to the caller's family.
 *
 * family_id is resolved server-side from the caller's membership.
 */
export const createChild = <ThrowOnError extends boolean = false>(options: Options<CreateChildData, ThrowOnError>): RequestResult<CreateChildResponses, CreateChildErrors, ThrowOnError> => (options.client ?? client).post<CreateChildResponses, CreateChildErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'x-user-id', type: 'apiKey' }],
    url: '/children',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Partially update a child's profile (name, grade, visibility defaults).
 *
 * Partial update (PATCH semantics): only supplied fields are changed.
 *
 * RLS ensures the caller can only update children in their own family.
 * Returns 404 if the child is not found or not accessible.
 */
export const updateChild = <ThrowOnError extends boolean = false>(options: Options<UpdateChildData, ThrowOnError>): RequestResult<UpdateChildResponses, UpdateChildErrors, ThrowOnError> => (options.client ?? client).patch<UpdateChildResponses, UpdateChildErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'x-user-id', type: 'apiKey' }],
    url: '/children/{child_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Archive a child (reversible soft-delete — hides cycles from the child).
 *
 * Sets archived_at = now().
 *
 * The child no longer appears in GET /children (active-only list).
 * RLS ensures the caller can only archive children in their own family.
 * Returns 404 if the child is not found, already archived, or not accessible.
 */
export const archiveChild = <ThrowOnError extends boolean = false>(options: Options<ArchiveChildData, ThrowOnError>): RequestResult<ArchiveChildResponses, ArchiveChildErrors, ThrowOnError> => (options.client ?? client).post<ArchiveChildResponses, ArchiveChildErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'x-user-id', type: 'apiKey' }],
    url: '/children/{child_id}/archive',
    ...options
});

/**
 * List subjects in the caller's family.
 */
export const listSubjects = <ThrowOnError extends boolean = false>(options?: Options<ListSubjectsData, ThrowOnError>): RequestResult<ListSubjectsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListSubjectsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'x-user-id', type: 'apiKey' }],
    url: '/subjects',
    ...options
});

/**
 * Add a subject for a child.
 *
 * family_id is resolved server-side from the caller's membership.
 *
 * ``name`` is freeform; the app never interprets it (ARCHITECTURE golden rule 4).
 */
export const createSubject = <ThrowOnError extends boolean = false>(options: Options<CreateSubjectData, ThrowOnError>): RequestResult<CreateSubjectResponses, CreateSubjectErrors, ThrowOnError> => (options.client ?? client).post<CreateSubjectResponses, CreateSubjectErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'x-user-id', type: 'apiKey' }],
    url: '/subjects',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List all cycles for the caller's family.
 */
export const listCycles = <ThrowOnError extends boolean = false>(options?: Options<ListCyclesData, ThrowOnError>): RequestResult<ListCyclesResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListCyclesResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'x-user-id', type: 'apiKey' }],
    url: '/cycles',
    ...options
});

/**
 * Create a new diagnostic cycle for a subject.
 *
 * Create a cycle in SCOPE_UPLOADED state.
 *
 * family_id is resolved server-side from the caller's membership (invariant 3).
 * ``scope_text`` is the text-first scope intake for this slice.
 */
export const createCycle = <ThrowOnError extends boolean = false>(options: Options<CreateCycleData, ThrowOnError>): RequestResult<CreateCycleResponses, CreateCycleErrors, ThrowOnError> => (options.client ?? client).post<CreateCycleResponses, CreateCycleErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'x-user-id', type: 'apiKey' }],
    url: '/cycles',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get a cycle by id, including its assessment(s) if present.
 */
export const getCycle = <ThrowOnError extends boolean = false>(options: Options<GetCycleData, ThrowOnError>): RequestResult<GetCycleResponses, GetCycleErrors, ThrowOnError> => (options.client ?? client).get<GetCycleResponses, GetCycleErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'x-user-id', type: 'apiKey' }],
    url: '/cycles/{cycle_id}',
    ...options
});

/**
 * Generate Variant-A assessment for a cycle; advances cycle state.
 *
 * Generate Variant-A using FakeClaude (live Claude is deferred).
 *
 * State machine:
 * SCOPE_UPLOADED → GENERATING_A  (before generation starts)
 * GENERATING_A   → PARENT_REVIEWS_DRAFT  (on success)
 *
 * On validation failure after retry, the cycle stays in GENERATING_A
 * and a structured error is returned (HTTP 422).
 */
export const generateAssessmentForCycle = <ThrowOnError extends boolean = false>(options: Options<GenerateAssessmentForCycleData, ThrowOnError>): RequestResult<GenerateAssessmentForCycleResponses, GenerateAssessmentForCycleErrors, ThrowOnError> => (options.client ?? client).post<GenerateAssessmentForCycleResponses, GenerateAssessmentForCycleErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'x-user-id', type: 'apiKey' }],
    url: '/cycles/{cycle_id}/generate',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Parent approves the draft — advances to APPROVED_PRINTED.
 *
 * PARENT_REVIEWS_DRAFT → APPROVED_PRINTED.
 *
 * Records ``parent_approval_at`` (now()) and optional ``note`` (golden rule 8).
 */
export const approveCycleDraft = <ThrowOnError extends boolean = false>(options: Options<ApproveCycleDraftData, ThrowOnError>): RequestResult<ApproveCycleDraftResponses, ApproveCycleDraftErrors, ThrowOnError> => (options.client ?? client).post<ApproveCycleDraftResponses, ApproveCycleDraftErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'x-user-id', type: 'apiKey' }],
    url: '/cycles/{cycle_id}/approve',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Return the memo-free child view of the approved assessment (cycle must be APPROVED_PRINTED).
 *
 * Serve the Variant-A assessment to the child in kiosk mode.
 *
 * Guards:
 * - Cycle exists in the caller's family (RLS enforced in repo layer).
 * - Cycle is in APPROVED_PRINTED — nothing is visible before parent approval
 * (golden rule 8).
 * - Assessment for this cycle exists (generation must have completed).
 *
 * Returns a ``ChildAssessmentView`` that contains NO answer keys, memo text,
 * method notes, accepted alternatives, or any other information that would
 * reveal the answers.
 */
export const getCaptureView = <ThrowOnError extends boolean = false>(options: Options<GetCaptureViewData, ThrowOnError>): RequestResult<GetCaptureViewResponses, GetCaptureViewErrors, ThrowOnError> => (options.client ?? client).get<GetCaptureViewResponses, GetCaptureViewErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'x-user-id', type: 'apiKey' }],
    url: '/cycles/{cycle_id}/capture',
    ...options
});

/**
 * Submit child answers; advances cycle APPROVED_PRINTED → ANSWERS_ENTERED.
 *
 * Accept the child's responses and persist the submission.
 *
 * Server-side guards (none of these trust any client flag):
 * 1. Cycle exists in the caller's family (RLS).
 * 2. Cycle is in APPROVED_PRINTED.
 * 3. body.child_id matches the cycle → subject → child_id chain.
 * 4. All qids in body.responses belong to the assessment.
 *
 * On success:
 * - Submission is persisted via SubmissionRepository.
 * - Cycle advances APPROVED_PRINTED → ANSWERS_ENTERED via cycle service.
 *
 * Grading is NOT triggered here (Phase 2).
 * proof_photo_paths are stored as-is; NEVER fed to grading (§10).
 */
export const createSubmission = <ThrowOnError extends boolean = false>(options: Options<CreateSubmissionData, ThrowOnError>): RequestResult<CreateSubmissionResponses, CreateSubmissionErrors, ThrowOnError> => (options.client ?? client).post<CreateSubmissionResponses, CreateSubmissionErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'x-user-id', type: 'apiKey' }],
    url: '/cycles/{cycle_id}/submissions',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Grade the cycle's submission; upserts question_marks and advances cycle ANSWERS_ENTERED → AUTO_MARKED.
 *
 * Grade the submission and upsert marks.
 *
 * Guards:
 * 1. Cycle exists in the caller's family (RLS).
 * 2. Cycle is in ANSWERS_ENTERED or AUTO_MARKED (idempotent re-grade).
 * 3. Submission exists for the cycle.
 * 4. Assessment exists for the cycle.
 *
 * Proof photos are NEVER read (ARCHITECTURE.md §10).
 */
export const gradeSubmissionMarks = <ThrowOnError extends boolean = false>(options: Options<GradeSubmissionMarksData, ThrowOnError>): RequestResult<GradeSubmissionMarksResponses, GradeSubmissionMarksErrors, ThrowOnError> => (options.client ?? client).post<GradeSubmissionMarksResponses, GradeSubmissionMarksErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'x-user-id', type: 'apiKey' }],
    url: '/cycles/{cycle_id}/grade',
    ...options
});

/**
 * List all question marks for the cycle, with question context for parent review.
 *
 * Return all marks for the cycle's submission.
 *
 * Includes question context (text, type, mark_rules) so the parent review
 * screen (Phase 3) can render each mark without re-fetching the assessment.
 */
export const listQuestionMarks = <ThrowOnError extends boolean = false>(options: Options<ListQuestionMarksData, ThrowOnError>): RequestResult<ListQuestionMarksResponses, ListQuestionMarksErrors, ThrowOnError> => (options.client ?? client).get<ListQuestionMarksResponses, ListQuestionMarksErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'x-user-id', type: 'apiKey' }],
    url: '/cycles/{cycle_id}/marks',
    ...options
});

/**
 * Parent override of a single question mark. Sets final_marks, reviewed_at, and overridden_at. On first call, transitions AUTO_MARKED → PARENT_REVIEW_MARKS.
 *
 * Apply a parent review patch to a single question mark.
 *
 * Guards:
 * 1. Cycle exists in the caller's family (RLS).
 * 2. Cycle is in AUTO_MARKED or PARENT_REVIEW_MARKS.
 * 3. The question mark exists for this cycle's submission.
 * 4. final_marks (if provided) must be <= marks_total.
 *
 * Transition: AUTO_MARKED → PARENT_REVIEW_MARKS on the first PATCH.
 * Already in PARENT_REVIEW_MARKS: no transition needed.
 */
export const reviewQuestionMark = <ThrowOnError extends boolean = false>(options: Options<ReviewQuestionMarkData, ThrowOnError>): RequestResult<ReviewQuestionMarkResponses, ReviewQuestionMarkErrors, ThrowOnError> => (options.client ?? client).patch<ReviewQuestionMarkResponses, ReviewQuestionMarkErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'x-user-id', type: 'apiKey' }],
    url: '/cycles/{cycle_id}/marks/{question_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Publish marks to the child. Requires all final_marks to be set. Freezes visibility snapshot. Transitions PARENT_REVIEW_MARKS → GAP_REPORT.
 *
 * Publish marks to the child (approval-gated, golden rule 8).
 *
 * Guards:
 * 1. Cycle exists in the caller's family (RLS).
 * 2. Cycle is in PARENT_REVIEW_MARKS.
 * 3. Every question mark has final_marks set — 409 with list of unresolved
 * question_ids if not.
 *
 * On success:
 * - Resolves child's visibility_defaults and merges with request overrides.
 * - Freezes the merged result as published_visibility in the cycle row.
 * - Records marks_published_at = now() (parent approval timestamp, golden rule 8).
 * - Transitions PARENT_REVIEW_MARKS → GAP_REPORT via cycle.py.
 *
 * NOTE: This endpoint does NOT build or return the child results view.
 * The future child results endpoint (Phase 4+) MUST:
 * - Read published_visibility server-side.
 * - Exclude ai_rationale from the child response when published_visibility.ai_rationale is False.
 * - Never expose correct_answer_rendered or memo fields to the child.
 */
export const publishMarks = <ThrowOnError extends boolean = false>(options: Options<PublishMarksData, ThrowOnError>): RequestResult<PublishMarksResponses, PublishMarksErrors, ThrowOnError> => (options.client ?? client).post<PublishMarksResponses, PublishMarksErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'x-user-id', type: 'apiKey' }],
    url: '/cycles/{cycle_id}/publish',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Return the stored gap report for a cycle. 404 if not yet generated.
 *
 * Return the persisted gap report.
 *
 * Guards:
 * 1. Cycle exists in the caller's family (RLS).
 * 2. Gap report row exists — 404 if not yet generated.
 */
export const getGapReport = <ThrowOnError extends boolean = false>(options: Options<GetGapReportData, ThrowOnError>): RequestResult<GetGapReportResponses, GetGapReportErrors, ThrowOnError> => (options.client ?? client).get<GetGapReportResponses, GetGapReportErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'x-user-id', type: 'apiKey' }],
    url: '/cycles/{cycle_id}/gap-report',
    ...options
});

/**
 * Derive the gap report from reviewed marks and upsert to storage. Idempotent. Cycle must be in GAP_REPORT or a later state.
 *
 * Derive and persist the gap report for a cycle.
 *
 * Guards:
 * 1. Cycle exists in the caller's family (RLS).
 * 2. Cycle is in GAP_REPORT or a later state (marks published).
 * 3. The cycle has a Variant-A assessment.
 * 4. The cycle has at least one graded mark.
 *
 * Derivation is deterministic — no Claude call.
 * final_marks is guaranteed set by the publish gate; any None value causes a
 * 500 (invariant violation) rather than silently producing a wrong report.
 */
export const generateGapReport = <ThrowOnError extends boolean = false>(options: Options<GenerateGapReportData, ThrowOnError>): RequestResult<GenerateGapReportResponses, GenerateGapReportErrors, ThrowOnError> => (options.client ?? client).post<GenerateGapReportResponses, GenerateGapReportErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'x-user-id', type: 'apiKey' }],
    url: '/cycles/{cycle_id}/gap-report',
    ...options
});
