// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Assessment
 */
export type Assessment = {
    /**
     * Schema Version
     */
    schema_version?: string;
    /**
     * Assessment Id
     */
    assessment_id: string;
    /**
     * Cycle Id
     */
    cycle_id: string;
    /**
     * Variant
     */
    variant: 'A' | 'B';
    /**
     * Subject
     *
     * Freeform; the app never interprets it.
     */
    subject: string;
    /**
     * Content Language
     *
     * ISO 639-1/2 lowercase, e.g. "en", "af", "fr", "zu".
     */
    content_language: string;
    /**
     * Grade Label
     *
     * Freeform, e.g. "Grade 5".
     */
    grade_label: string;
    /**
     * Title
     */
    title: string;
    /**
     * Duration Minutes
     */
    duration_minutes: number;
    /**
     * Instructions
     */
    instructions?: Array<string>;
    /**
     * Declared Total Marks
     */
    declared_total_marks: number;
    /**
     * Sections
     */
    sections: Array<Section>;
    /**
     * Computed Total Marks
     */
    readonly computed_total_marks: number;
};

/**
 * Blank
 */
export type Blank = {
    /**
     * Accepted
     *
     * All accepted answers/spellings.
     */
    accepted: Array<string>;
    /**
     * Value Type
     */
    value_type?: 'word' | 'number';
    /**
     * Case Sensitive
     */
    case_sensitive?: boolean;
};

/**
 * BootstrapResponse
 *
 * Response from POST /families (bootstrap).
 */
export type BootstrapResponse = {
    family: FamilyResponse;
    /**
     * Child Id
     */
    child_id?: string | null;
};

/**
 * CalculationAnswer
 */
export type CalculationAnswer = {
    /**
     * Kind
     */
    kind?: 'calculation';
    /**
     * Final Answer
     */
    final_answer: string;
    /**
     * Unit
     */
    unit?: string | null;
    /**
     * Tolerance
     *
     * Numeric tolerance if any.
     */
    tolerance?: number | null;
    /**
     * Number Sentence
     *
     * Full number sentence for the memo (word problems).
     */
    number_sentence?: string | null;
    /**
     * Method Steps
     *
     * Worked steps; basis for method marks.
     */
    method_steps?: Array<string>;
};

/**
 * ChildCreate
 *
 * Create a child.  family_id is derived server-side; never from the client.
 */
export type ChildCreate = {
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Grade Label
     */
    grade_label: string;
    /**
     * Initial publish-gate toggle defaults; uses standard defaults when omitted.
     */
    visibility_defaults?: VisibilityDefaults;
};

/**
 * ChildResponse
 */
export type ChildResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Family Id
     */
    family_id: string;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Grade Label
     */
    grade_label: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Archived At
     */
    archived_at?: string | null;
    visibility_defaults?: VisibilityDefaults;
};

/**
 * ChildUpdate
 *
 * PATCH payload for child profile (all fields optional — partial update semantics).
 */
export type ChildUpdate = {
    /**
     * Display Name
     */
    display_name?: string | null;
    /**
     * Grade Label
     */
    grade_label?: string | null;
    visibility_defaults?: VisibilityDefaults | null;
};

/**
 * CycleApprove
 *
 * Parent approval payload for POST /cycles/{id}/approve.
 */
export type CycleApprove = {
    /**
     * Note
     *
     * Optional parent note recorded with the approval timestamp.
     */
    note?: string | null;
};

/**
 * CycleCreate
 *
 * Create a cycle.  family_id is derived server-side.
 *
 * ``scope_text`` is the text-first scope intake (no Storage upload this slice).
 */
export type CycleCreate = {
    /**
     * Subject Id
     */
    subject_id: string;
    /**
     * Scope Text
     *
     * Educational scope text.  Text-first intake (no file upload this slice).
     */
    scope_text: string;
};

/**
 * CycleResponse
 */
export type CycleResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Family Id
     */
    family_id: string;
    /**
     * Subject Id
     */
    subject_id: string;
    state: CycleState;
    /**
     * Scope Text
     */
    scope_text?: string | null;
    /**
     * Parent Approval At
     */
    parent_approval_at?: string | null;
    /**
     * Parent Approval Note
     */
    parent_approval_note?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Assessments
     *
     * Assessment document(s) for this cycle; populated on detail endpoint, empty on list views.
     */
    assessments?: Array<Assessment>;
};

/**
 * CycleState
 */
export type CycleState = 'SCOPE_UPLOADED' | 'GENERATING_A' | 'PARENT_REVIEWS_DRAFT' | 'APPROVED_PRINTED' | 'ANSWERS_ENTERED' | 'AUTO_MARKED' | 'PARENT_REVIEW_MARKS' | 'GAP_REPORT' | 'GENERATING_STUDY_PACK' | 'STUDY_PACK_DONE' | 'GENERATING_B' | 'CYCLE_COMPLETE';

/**
 * Difficulty
 */
export type Difficulty = 'easy' | 'medium' | 'challenging';

/**
 * ExtendedResponseAnswer
 */
export type ExtendedResponseAnswer = {
    /**
     * Kind
     */
    kind?: 'extended_response';
    /**
     * Model Answer
     */
    model_answer: string;
    /**
     * Rubric
     */
    rubric: Array<RubricPoint>;
    /**
     * Required Structure
     *
     * e.g. "P.E.E. (Point, Evidence, Explain)".
     */
    required_structure?: string | null;
};

/**
 * FamilyCreate
 *
 * Bootstrap request — creates a family + the caller's membership row.
 *
 * Optionally creates the first child in the same transaction.
 * child_name and grade_label must both be provided or both omitted.
 */
export type FamilyCreate = {
    /**
     * Family Name
     *
     * Display name for the family.
     */
    family_name: string;
    /**
     * Child Name
     */
    child_name?: string | null;
    /**
     * Grade Label
     */
    grade_label?: string | null;
};

/**
 * FamilyResponse
 */
export type FamilyResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * FillBlankAnswer
 */
export type FillBlankAnswer = {
    /**
     * Kind
     */
    kind?: 'fill_blank';
    /**
     * Blanks
     */
    blanks: Array<Blank>;
};

/**
 * GenerateAssessmentRequest
 *
 * Caller-supplied scope for a new Variant-A assessment.
 */
export type GenerateAssessmentRequest = {
    /**
     * Cycle Id
     *
     * The cycle this assessment belongs to.
     */
    cycle_id: string;
    /**
     * Scope Text
     *
     * Educational scope (topic, grade, curriculum notes). Treated as untrusted.
     */
    scope_text: string;
};

/**
 * GenerateAssessmentResponse
 *
 * Result of a generation call — either a valid assessment or a structured error.
 */
export type GenerateAssessmentResponse = {
    /**
     * Ok
     */
    ok: boolean;
    assessment?: Assessment | null;
    /**
     * Issues
     */
    issues?: Array<ValidationIssue>;
    /**
     * Error
     */
    error?: string | null;
};

/**
 * GradingPath
 */
export type GradingPath = 'auto' | 'auto_fuzzy' | 'claude_assist';

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthStatus
 */
export type HealthStatus = {
    /**
     * Status
     */
    status?: 'ok';
    /**
     * App Name
     */
    app_name: string;
    /**
     * Version
     */
    version: string;
};

/**
 * LabellingAnswer
 */
export type LabellingAnswer = {
    /**
     * Kind
     */
    kind?: 'labelling';
    /**
     * Positions
     *
     * Position number (as printed on diagram) -> correct term.
     */
    positions: {
        [key: string]: string;
    };
    /**
     * Term Bank
     *
     * Optional word bank.
     */
    term_bank?: Array<string>;
    /**
     * Diagram Asset
     *
     * Storage path or asset id of the diagram.
     */
    diagram_asset?: string | null;
};

/**
 * MarkRules
 */
export type MarkRules = {
    /**
     * Total
     */
    total: number;
    /**
     * Answer Marks
     */
    answer_marks?: number | null;
    /**
     * Method Marks
     */
    method_marks?: number | null;
    /**
     * Tick Allocation
     *
     * Memo note, e.g. "1 tick method, 1 tick answer".
     */
    tick_allocation?: string | null;
};

/**
 * MatchingAnswer
 */
export type MatchingAnswer = {
    /**
     * Kind
     */
    kind?: 'matching';
    /**
     * Left
     */
    left: Array<string>;
    /**
     * Right
     */
    right: Array<string>;
    /**
     * Correct Pairs
     *
     * left index -> right index. right may contain distractor extras.
     */
    correct_pairs: {
        [key: string]: number;
    };
};

/**
 * McqAnswer
 */
export type McqAnswer = {
    /**
     * Kind
     */
    kind?: 'mcq';
    /**
     * Options
     */
    options: Array<string>;
    /**
     * Correct Index
     */
    correct_index: number;
    /**
     * Distractor Notes
     *
     * Why each wrong option is a plausible common error (memo aid).
     */
    distractor_notes?: {
        [key: string]: string;
    };
};

/**
 * Memo
 */
export type Memo = {
    /**
     * Worked Solution
     */
    worked_solution?: string | null;
    /**
     * Marker Tip
     */
    marker_tip?: string | null;
};

/**
 * OrderingAnswer
 */
export type OrderingAnswer = {
    /**
     * Kind
     */
    kind?: 'ordering';
    /**
     * Items
     *
     * As printed (shuffled).
     */
    items: Array<string>;
    /**
     * Correct Order
     *
     * Indices of `items` in correct sequence.
     */
    correct_order: Array<number>;
};

/**
 * Question
 */
export type Question = {
    /**
     * Qid
     *
     * Stable unique id, e.g. 'A.3' or a uuid.
     */
    qid: string;
    /**
     * Number
     *
     * As printed: "3", "3.1", "3a".
     */
    number: string;
    /**
     * Text
     */
    text: string;
    question_type: QuestionType;
    difficulty: Difficulty;
    /**
     * Answer
     */
    answer: ({
        kind: 'mcq';
    } & McqAnswer) | ({
        kind: 'true_false';
    } & TrueFalseAnswer) | ({
        kind: 'matching';
    } & MatchingAnswer) | ({
        kind: 'ordering';
    } & OrderingAnswer) | ({
        kind: 'fill_blank';
    } & FillBlankAnswer) | ({
        kind: 'short_answer';
    } & ShortAnswerSpec) | ({
        kind: 'calculation';
    } & CalculationAnswer) | ({
        kind: 'table_completion';
    } & TableCompletionAnswer) | ({
        kind: 'labelling';
    } & LabellingAnswer) | ({
        kind: 'extended_response';
    } & ExtendedResponseAnswer);
    mark_rules: MarkRules;
    render_hints?: RenderHints;
    memo?: Memo;
    /**
     * Gap Tags
     *
     * Gap ids this question deliberately retests (Variant B retargeting).
     */
    gap_tags?: Array<string>;
    readonly grading_path: GradingPath;
};

/**
 * QuestionType
 */
export type QuestionType = 'mcq' | 'true_false' | 'matching' | 'ordering' | 'fill_blank' | 'short_answer' | 'calculation' | 'table_completion' | 'labelling' | 'extended_response';

/**
 * RenderHints
 */
export type RenderHints = {
    /**
     * Working Lines
     *
     * Blank working lines to print.
     */
    working_lines?: number;
    /**
     * Layout
     *
     * e.g. "two_column", "table".
     */
    layout?: string | null;
    /**
     * Diagram Prompt
     *
     * Image-generation prompt box if a visual aid is needed (no image gen in MVP).
     */
    diagram_prompt?: string | null;
    /**
     * Page Break Before
     */
    page_break_before?: boolean;
};

/**
 * RubricPoint
 */
export type RubricPoint = {
    /**
     * Point
     */
    point: string;
    /**
     * Marks
     */
    marks: number;
};

/**
 * Section
 */
export type Section = {
    /**
     * Label
     *
     * "A", "B", ...
     */
    label: string;
    /**
     * Title
     */
    title: string;
    /**
     * Instructions
     */
    instructions?: string | null;
    /**
     * Declared Marks
     */
    declared_marks: number;
    /**
     * Questions
     */
    questions: Array<Question>;
    /**
     * Computed Marks
     */
    readonly computed_marks: number;
};

/**
 * ShortAnswerSpec
 */
export type ShortAnswerSpec = {
    /**
     * Kind
     */
    kind?: 'short_answer';
    /**
     * Accepted
     *
     * Model answers/alternatives.
     */
    accepted: Array<string>;
    /**
     * Required Keywords
     */
    required_keywords?: Array<string>;
    /**
     * Marker Guidance
     */
    marker_guidance?: string | null;
};

/**
 * SubjectCreate
 *
 * Create a subject.  family_id is derived server-side.
 *
 * ``name`` is freeform (ARCHITECTURE golden rule 4: no subject == branches).
 * ``content_language`` drives generation/grading language (ISO 639-1/2 lowercase).
 */
export type SubjectCreate = {
    /**
     * Child Id
     */
    child_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Content Language
     *
     * ISO 639-1/2 lowercase, e.g. 'en', 'af'.
     */
    content_language: string;
};

/**
 * SubjectResponse
 */
export type SubjectResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Family Id
     */
    family_id: string;
    /**
     * Child Id
     */
    child_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Content Language
     */
    content_language: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * TableCell
 */
export type TableCell = {
    /**
     * Row
     */
    row: number;
    /**
     * Col
     */
    col: number;
    /**
     * Accepted
     */
    accepted: Array<string>;
    /**
     * Half Mark
     *
     * 0.5 mark per cell if True.
     */
    half_mark?: boolean;
};

/**
 * TableCompletionAnswer
 */
export type TableCompletionAnswer = {
    /**
     * Kind
     */
    kind?: 'table_completion';
    /**
     * Row Headers
     */
    row_headers: Array<string>;
    /**
     * Col Headers
     */
    col_headers: Array<string>;
    /**
     * Cells
     *
     * Only cells the child fills.
     */
    cells: Array<TableCell>;
    /**
     * Format Example Row
     *
     * Render one pre-completed row (discovery: table format misreads).
     */
    format_example_row?: boolean;
};

/**
 * TrueFalseAnswer
 */
export type TrueFalseAnswer = {
    /**
     * Kind
     */
    kind?: 'true_false';
    /**
     * Is True
     */
    is_true: boolean;
    /**
     * Requires Correction
     *
     * If a false statement must be corrected for the second mark.
     */
    requires_correction?: boolean;
    /**
     * Corrected Statement
     */
    corrected_statement?: string | null;
};

/**
 * ValidateAssessmentRequest
 *
 * The one deliberate raw-dict entry point: an assessment payload of
 * unknown validity, submitted for schema validation.
 */
export type ValidateAssessmentRequest = {
    /**
     * Assessment
     */
    assessment: {
        [key: string]: unknown;
    };
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * ValidationIssue
 */
export type ValidationIssue = {
    /**
     * Loc
     */
    loc: Array<string | number>;
    /**
     * Msg
     */
    msg: string;
    /**
     * Type
     */
    type: string;
};

/**
 * ValidationResult
 */
export type ValidationResult = {
    /**
     * Valid
     */
    valid: boolean;
    /**
     * Schema Version
     */
    schema_version: string;
    /**
     * Issues
     */
    issues?: Array<ValidationIssue>;
};

/**
 * VisibilityDefaults
 *
 * Per-child toggle defaults for the publish gate (Settings p13).
 *
 * Stored as JSONB in children.visibility_defaults.
 * Not yet consumed by any downstream gate — modelled plainly, no coupling.
 *
 * Design defaults (p13): accuracy/effort/growing ON, ai_rationale OFF.
 */
export type VisibilityDefaults = {
    /**
     * Accuracy
     */
    accuracy?: boolean;
    /**
     * Effort
     */
    effort?: boolean;
    /**
     * Growing
     */
    growing?: boolean;
    /**
     * Ai Rationale
     */
    ai_rationale?: boolean;
};

/**
 * Assessment
 */
export type AssessmentWritable = {
    /**
     * Schema Version
     */
    schema_version?: string;
    /**
     * Assessment Id
     */
    assessment_id: string;
    /**
     * Cycle Id
     */
    cycle_id: string;
    /**
     * Variant
     */
    variant: 'A' | 'B';
    /**
     * Subject
     *
     * Freeform; the app never interprets it.
     */
    subject: string;
    /**
     * Content Language
     *
     * ISO 639-1/2 lowercase, e.g. "en", "af", "fr", "zu".
     */
    content_language: string;
    /**
     * Grade Label
     *
     * Freeform, e.g. "Grade 5".
     */
    grade_label: string;
    /**
     * Title
     */
    title: string;
    /**
     * Duration Minutes
     */
    duration_minutes: number;
    /**
     * Instructions
     */
    instructions?: Array<string>;
    /**
     * Declared Total Marks
     */
    declared_total_marks: number;
    /**
     * Sections
     */
    sections: Array<SectionWritable>;
};

/**
 * CycleResponse
 */
export type CycleResponseWritable = {
    /**
     * Id
     */
    id: string;
    /**
     * Family Id
     */
    family_id: string;
    /**
     * Subject Id
     */
    subject_id: string;
    state: CycleState;
    /**
     * Scope Text
     */
    scope_text?: string | null;
    /**
     * Parent Approval At
     */
    parent_approval_at?: string | null;
    /**
     * Parent Approval Note
     */
    parent_approval_note?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Assessments
     *
     * Assessment document(s) for this cycle; populated on detail endpoint, empty on list views.
     */
    assessments?: Array<AssessmentWritable>;
};

/**
 * GenerateAssessmentResponse
 *
 * Result of a generation call — either a valid assessment or a structured error.
 */
export type GenerateAssessmentResponseWritable = {
    /**
     * Ok
     */
    ok: boolean;
    assessment?: AssessmentWritable | null;
    /**
     * Issues
     */
    issues?: Array<ValidationIssue>;
    /**
     * Error
     */
    error?: string | null;
};

/**
 * Question
 */
export type QuestionWritable = {
    /**
     * Qid
     *
     * Stable unique id, e.g. 'A.3' or a uuid.
     */
    qid: string;
    /**
     * Number
     *
     * As printed: "3", "3.1", "3a".
     */
    number: string;
    /**
     * Text
     */
    text: string;
    question_type: QuestionType;
    difficulty: Difficulty;
    /**
     * Answer
     */
    answer: ({
        kind: 'mcq';
    } & McqAnswer) | ({
        kind: 'true_false';
    } & TrueFalseAnswer) | ({
        kind: 'matching';
    } & MatchingAnswer) | ({
        kind: 'ordering';
    } & OrderingAnswer) | ({
        kind: 'fill_blank';
    } & FillBlankAnswer) | ({
        kind: 'short_answer';
    } & ShortAnswerSpec) | ({
        kind: 'calculation';
    } & CalculationAnswer) | ({
        kind: 'table_completion';
    } & TableCompletionAnswer) | ({
        kind: 'labelling';
    } & LabellingAnswer) | ({
        kind: 'extended_response';
    } & ExtendedResponseAnswer);
    mark_rules: MarkRules;
    render_hints?: RenderHints;
    memo?: Memo;
    /**
     * Gap Tags
     *
     * Gap ids this question deliberately retests (Variant B retargeting).
     */
    gap_tags?: Array<string>;
};

/**
 * Section
 */
export type SectionWritable = {
    /**
     * Label
     *
     * "A", "B", ...
     */
    label: string;
    /**
     * Title
     */
    title: string;
    /**
     * Instructions
     */
    instructions?: string | null;
    /**
     * Declared Marks
     */
    declared_marks: number;
    /**
     * Questions
     */
    questions: Array<QuestionWritable>;
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * Successful Response
     */
    200: HealthStatus;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type ValidateAssessmentData = {
    body: ValidateAssessmentRequest;
    path?: never;
    query?: never;
    url: '/assessments/validate';
};

export type ValidateAssessmentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ValidateAssessmentError = ValidateAssessmentErrors[keyof ValidateAssessmentErrors];

export type ValidateAssessmentResponses = {
    /**
     * Successful Response
     */
    200: ValidationResult;
};

export type ValidateAssessmentResponse = ValidateAssessmentResponses[keyof ValidateAssessmentResponses];

export type GenerateAssessmentData = {
    body: GenerateAssessmentRequest;
    path?: never;
    query?: never;
    url: '/assessments/generate';
};

export type GenerateAssessmentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GenerateAssessmentError = GenerateAssessmentErrors[keyof GenerateAssessmentErrors];

export type GenerateAssessmentResponses = {
    /**
     * Successful Response
     */
    201: GenerateAssessmentResponse;
};

export type GenerateAssessmentResponse2 = GenerateAssessmentResponses[keyof GenerateAssessmentResponses];

export type ListFamiliesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/families';
};

export type ListFamiliesResponses = {
    /**
     * Response List Families
     *
     * Successful Response
     */
    200: Array<FamilyResponse>;
};

export type ListFamiliesResponse = ListFamiliesResponses[keyof ListFamiliesResponses];

export type BootstrapFamilyData = {
    body: FamilyCreate;
    path?: never;
    query?: never;
    url: '/families';
};

export type BootstrapFamilyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BootstrapFamilyError = BootstrapFamilyErrors[keyof BootstrapFamilyErrors];

export type BootstrapFamilyResponses = {
    /**
     * Successful Response
     */
    201: BootstrapResponse;
};

export type BootstrapFamilyResponse = BootstrapFamilyResponses[keyof BootstrapFamilyResponses];

export type ListChildrenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/children';
};

export type ListChildrenResponses = {
    /**
     * Response List Children
     *
     * Successful Response
     */
    200: Array<ChildResponse>;
};

export type ListChildrenResponse = ListChildrenResponses[keyof ListChildrenResponses];

export type CreateChildData = {
    body: ChildCreate;
    path?: never;
    query?: never;
    url: '/children';
};

export type CreateChildErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateChildError = CreateChildErrors[keyof CreateChildErrors];

export type CreateChildResponses = {
    /**
     * Successful Response
     */
    201: ChildResponse;
};

export type CreateChildResponse = CreateChildResponses[keyof CreateChildResponses];

export type UpdateChildData = {
    body: ChildUpdate;
    path: {
        /**
         * Child Id
         */
        child_id: string;
    };
    query?: never;
    url: '/children/{child_id}';
};

export type UpdateChildErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateChildError = UpdateChildErrors[keyof UpdateChildErrors];

export type UpdateChildResponses = {
    /**
     * Successful Response
     */
    200: ChildResponse;
};

export type UpdateChildResponse = UpdateChildResponses[keyof UpdateChildResponses];

export type ArchiveChildData = {
    body?: never;
    path: {
        /**
         * Child Id
         */
        child_id: string;
    };
    query?: never;
    url: '/children/{child_id}/archive';
};

export type ArchiveChildErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ArchiveChildError = ArchiveChildErrors[keyof ArchiveChildErrors];

export type ArchiveChildResponses = {
    /**
     * Successful Response
     */
    200: ChildResponse;
};

export type ArchiveChildResponse = ArchiveChildResponses[keyof ArchiveChildResponses];

export type ListSubjectsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/subjects';
};

export type ListSubjectsResponses = {
    /**
     * Response List Subjects
     *
     * Successful Response
     */
    200: Array<SubjectResponse>;
};

export type ListSubjectsResponse = ListSubjectsResponses[keyof ListSubjectsResponses];

export type CreateSubjectData = {
    body: SubjectCreate;
    path?: never;
    query?: never;
    url: '/subjects';
};

export type CreateSubjectErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateSubjectError = CreateSubjectErrors[keyof CreateSubjectErrors];

export type CreateSubjectResponses = {
    /**
     * Successful Response
     */
    201: SubjectResponse;
};

export type CreateSubjectResponse = CreateSubjectResponses[keyof CreateSubjectResponses];

export type ListCyclesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/cycles';
};

export type ListCyclesResponses = {
    /**
     * Response List Cycles
     *
     * Successful Response
     */
    200: Array<CycleResponse>;
};

export type ListCyclesResponse = ListCyclesResponses[keyof ListCyclesResponses];

export type CreateCycleData = {
    body: CycleCreate;
    path?: never;
    query?: never;
    url: '/cycles';
};

export type CreateCycleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateCycleError = CreateCycleErrors[keyof CreateCycleErrors];

export type CreateCycleResponses = {
    /**
     * Successful Response
     */
    201: CycleResponse;
};

export type CreateCycleResponse = CreateCycleResponses[keyof CreateCycleResponses];

export type GetCycleData = {
    body?: never;
    path: {
        /**
         * Cycle Id
         */
        cycle_id: string;
    };
    query?: never;
    url: '/cycles/{cycle_id}';
};

export type GetCycleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCycleError = GetCycleErrors[keyof GetCycleErrors];

export type GetCycleResponses = {
    /**
     * Successful Response
     */
    200: CycleResponse;
};

export type GetCycleResponse = GetCycleResponses[keyof GetCycleResponses];

export type GenerateAssessmentForCycleData = {
    body: GenerateAssessmentRequest;
    path: {
        /**
         * Cycle Id
         */
        cycle_id: string;
    };
    query?: never;
    url: '/cycles/{cycle_id}/generate';
};

export type GenerateAssessmentForCycleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GenerateAssessmentForCycleError = GenerateAssessmentForCycleErrors[keyof GenerateAssessmentForCycleErrors];

export type GenerateAssessmentForCycleResponses = {
    /**
     * Successful Response
     */
    201: GenerateAssessmentResponse;
};

export type GenerateAssessmentForCycleResponse = GenerateAssessmentForCycleResponses[keyof GenerateAssessmentForCycleResponses];

export type ApproveCycleDraftData = {
    body: CycleApprove;
    path: {
        /**
         * Cycle Id
         */
        cycle_id: string;
    };
    query?: never;
    url: '/cycles/{cycle_id}/approve';
};

export type ApproveCycleDraftErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApproveCycleDraftError = ApproveCycleDraftErrors[keyof ApproveCycleDraftErrors];

export type ApproveCycleDraftResponses = {
    /**
     * Successful Response
     */
    200: CycleResponse;
};

export type ApproveCycleDraftResponse = ApproveCycleDraftResponses[keyof ApproveCycleDraftResponses];
