/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ResultsCycleIdRouteImport } from './routes/results/$cycleId'
import { Route as CyclesNewRouteImport } from './routes/cycles/new'
import { Route as CyclesCycleIdRouteImport } from './routes/cycles/$cycleId'
import { Route as CaptureCycleIdRouteImport } from './routes/capture/$cycleId'
import { Route as SettingsChildrenNewRouteImport } from './routes/settings/children/new'
import { Route as SettingsChildrenChildIdRouteImport } from './routes/settings/children/$childId'
import { Route as CyclesCycleIdStudyPackRouteImport } from './routes/cycles/$cycleId.study-pack'
import { Route as CyclesCycleIdReviewRouteImport } from './routes/cycles/$cycleId.review'
import { Route as CyclesCycleIdPublishRouteImport } from './routes/cycles/$cycleId.publish'
import { Route as CyclesCycleIdGapReportRouteImport } from './routes/cycles/$cycleId.gap-report'
import { Route as CyclesCycleIdComparisonRouteImport } from './routes/cycles/$cycleId.comparison'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsCycleIdRoute = ResultsCycleIdRouteImport.update({
  id: '/results/$cycleId',
  path: '/results/$cycleId',
  getParentRoute: () => rootRouteImport,
} as any)
const CyclesNewRoute = CyclesNewRouteImport.update({
  id: '/cycles/new',
  path: '/cycles/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CyclesCycleIdRoute = CyclesCycleIdRouteImport.update({
  id: '/cycles/$cycleId',
  path: '/cycles/$cycleId',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureCycleIdRoute = CaptureCycleIdRouteImport.update({
  id: '/capture/$cycleId',
  path: '/capture/$cycleId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsChildrenNewRoute = SettingsChildrenNewRouteImport.update({
  id: '/settings/children/new',
  path: '/settings/children/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsChildrenChildIdRoute = SettingsChildrenChildIdRouteImport.update({
  id: '/settings/children/$childId',
  path: '/settings/children/$childId',
  getParentRoute: () => rootRouteImport,
} as any)
const CyclesCycleIdStudyPackRoute = CyclesCycleIdStudyPackRouteImport.update({
  id: '/study-pack',
  path: '/study-pack',
  getParentRoute: () => CyclesCycleIdRoute,
} as any)
const CyclesCycleIdReviewRoute = CyclesCycleIdReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => CyclesCycleIdRoute,
} as any)
const CyclesCycleIdPublishRoute = CyclesCycleIdPublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => CyclesCycleIdRoute,
} as any)
const CyclesCycleIdGapReportRoute = CyclesCycleIdGapReportRouteImport.update({
  id: '/gap-report',
  path: '/gap-report',
  getParentRoute: () => CyclesCycleIdRoute,
} as any)
const CyclesCycleIdComparisonRoute = CyclesCycleIdComparisonRouteImport.update({
  id: '/comparison',
  path: '/comparison',
  getParentRoute: () => CyclesCycleIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/capture/$cycleId': typeof CaptureCycleIdRoute
  '/cycles/$cycleId': typeof CyclesCycleIdRouteWithChildren
  '/cycles/new': typeof CyclesNewRoute
  '/results/$cycleId': typeof ResultsCycleIdRoute
  '/settings/': typeof SettingsIndexRoute
  '/cycles/$cycleId/comparison': typeof CyclesCycleIdComparisonRoute
  '/cycles/$cycleId/gap-report': typeof CyclesCycleIdGapReportRoute
  '/cycles/$cycleId/publish': typeof CyclesCycleIdPublishRoute
  '/cycles/$cycleId/review': typeof CyclesCycleIdReviewRoute
  '/cycles/$cycleId/study-pack': typeof CyclesCycleIdStudyPackRoute
  '/settings/children/$childId': typeof SettingsChildrenChildIdRoute
  '/settings/children/new': typeof SettingsChildrenNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/capture/$cycleId': typeof CaptureCycleIdRoute
  '/cycles/$cycleId': typeof CyclesCycleIdRouteWithChildren
  '/cycles/new': typeof CyclesNewRoute
  '/results/$cycleId': typeof ResultsCycleIdRoute
  '/settings': typeof SettingsIndexRoute
  '/cycles/$cycleId/comparison': typeof CyclesCycleIdComparisonRoute
  '/cycles/$cycleId/gap-report': typeof CyclesCycleIdGapReportRoute
  '/cycles/$cycleId/publish': typeof CyclesCycleIdPublishRoute
  '/cycles/$cycleId/review': typeof CyclesCycleIdReviewRoute
  '/cycles/$cycleId/study-pack': typeof CyclesCycleIdStudyPackRoute
  '/settings/children/$childId': typeof SettingsChildrenChildIdRoute
  '/settings/children/new': typeof SettingsChildrenNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/capture/$cycleId': typeof CaptureCycleIdRoute
  '/cycles/$cycleId': typeof CyclesCycleIdRouteWithChildren
  '/cycles/new': typeof CyclesNewRoute
  '/results/$cycleId': typeof ResultsCycleIdRoute
  '/settings/': typeof SettingsIndexRoute
  '/cycles/$cycleId/comparison': typeof CyclesCycleIdComparisonRoute
  '/cycles/$cycleId/gap-report': typeof CyclesCycleIdGapReportRoute
  '/cycles/$cycleId/publish': typeof CyclesCycleIdPublishRoute
  '/cycles/$cycleId/review': typeof CyclesCycleIdReviewRoute
  '/cycles/$cycleId/study-pack': typeof CyclesCycleIdStudyPackRoute
  '/settings/children/$childId': typeof SettingsChildrenChildIdRoute
  '/settings/children/new': typeof SettingsChildrenNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/capture/$cycleId'
    | '/cycles/$cycleId'
    | '/cycles/new'
    | '/results/$cycleId'
    | '/settings/'
    | '/cycles/$cycleId/comparison'
    | '/cycles/$cycleId/gap-report'
    | '/cycles/$cycleId/publish'
    | '/cycles/$cycleId/review'
    | '/cycles/$cycleId/study-pack'
    | '/settings/children/$childId'
    | '/settings/children/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/capture/$cycleId'
    | '/cycles/$cycleId'
    | '/cycles/new'
    | '/results/$cycleId'
    | '/settings'
    | '/cycles/$cycleId/comparison'
    | '/cycles/$cycleId/gap-report'
    | '/cycles/$cycleId/publish'
    | '/cycles/$cycleId/review'
    | '/cycles/$cycleId/study-pack'
    | '/settings/children/$childId'
    | '/settings/children/new'
  id:
    | '__root__'
    | '/'
    | '/capture/$cycleId'
    | '/cycles/$cycleId'
    | '/cycles/new'
    | '/results/$cycleId'
    | '/settings/'
    | '/cycles/$cycleId/comparison'
    | '/cycles/$cycleId/gap-report'
    | '/cycles/$cycleId/publish'
    | '/cycles/$cycleId/review'
    | '/cycles/$cycleId/study-pack'
    | '/settings/children/$childId'
    | '/settings/children/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaptureCycleIdRoute: typeof CaptureCycleIdRoute
  CyclesCycleIdRoute: typeof CyclesCycleIdRouteWithChildren
  CyclesNewRoute: typeof CyclesNewRoute
  ResultsCycleIdRoute: typeof ResultsCycleIdRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SettingsChildrenChildIdRoute: typeof SettingsChildrenChildIdRoute
  SettingsChildrenNewRoute: typeof SettingsChildrenNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$cycleId': {
      id: '/results/$cycleId'
      path: '/results/$cycleId'
      fullPath: '/results/$cycleId'
      preLoaderRoute: typeof ResultsCycleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cycles/new': {
      id: '/cycles/new'
      path: '/cycles/new'
      fullPath: '/cycles/new'
      preLoaderRoute: typeof CyclesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cycles/$cycleId': {
      id: '/cycles/$cycleId'
      path: '/cycles/$cycleId'
      fullPath: '/cycles/$cycleId'
      preLoaderRoute: typeof CyclesCycleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture/$cycleId': {
      id: '/capture/$cycleId'
      path: '/capture/$cycleId'
      fullPath: '/capture/$cycleId'
      preLoaderRoute: typeof CaptureCycleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/children/new': {
      id: '/settings/children/new'
      path: '/settings/children/new'
      fullPath: '/settings/children/new'
      preLoaderRoute: typeof SettingsChildrenNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/children/$childId': {
      id: '/settings/children/$childId'
      path: '/settings/children/$childId'
      fullPath: '/settings/children/$childId'
      preLoaderRoute: typeof SettingsChildrenChildIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cycles/$cycleId/study-pack': {
      id: '/cycles/$cycleId/study-pack'
      path: '/study-pack'
      fullPath: '/cycles/$cycleId/study-pack'
      preLoaderRoute: typeof CyclesCycleIdStudyPackRouteImport
      parentRoute: typeof CyclesCycleIdRoute
    }
    '/cycles/$cycleId/review': {
      id: '/cycles/$cycleId/review'
      path: '/review'
      fullPath: '/cycles/$cycleId/review'
      preLoaderRoute: typeof CyclesCycleIdReviewRouteImport
      parentRoute: typeof CyclesCycleIdRoute
    }
    '/cycles/$cycleId/publish': {
      id: '/cycles/$cycleId/publish'
      path: '/publish'
      fullPath: '/cycles/$cycleId/publish'
      preLoaderRoute: typeof CyclesCycleIdPublishRouteImport
      parentRoute: typeof CyclesCycleIdRoute
    }
    '/cycles/$cycleId/gap-report': {
      id: '/cycles/$cycleId/gap-report'
      path: '/gap-report'
      fullPath: '/cycles/$cycleId/gap-report'
      preLoaderRoute: typeof CyclesCycleIdGapReportRouteImport
      parentRoute: typeof CyclesCycleIdRoute
    }
    '/cycles/$cycleId/comparison': {
      id: '/cycles/$cycleId/comparison'
      path: '/comparison'
      fullPath: '/cycles/$cycleId/comparison'
      preLoaderRoute: typeof CyclesCycleIdComparisonRouteImport
      parentRoute: typeof CyclesCycleIdRoute
    }
  }
}

interface CyclesCycleIdRouteChildren {
  CyclesCycleIdComparisonRoute: typeof CyclesCycleIdComparisonRoute
  CyclesCycleIdGapReportRoute: typeof CyclesCycleIdGapReportRoute
  CyclesCycleIdPublishRoute: typeof CyclesCycleIdPublishRoute
  CyclesCycleIdReviewRoute: typeof CyclesCycleIdReviewRoute
  CyclesCycleIdStudyPackRoute: typeof CyclesCycleIdStudyPackRoute
}

const CyclesCycleIdRouteChildren: CyclesCycleIdRouteChildren = {
  CyclesCycleIdComparisonRoute: CyclesCycleIdComparisonRoute,
  CyclesCycleIdGapReportRoute: CyclesCycleIdGapReportRoute,
  CyclesCycleIdPublishRoute: CyclesCycleIdPublishRoute,
  CyclesCycleIdReviewRoute: CyclesCycleIdReviewRoute,
  CyclesCycleIdStudyPackRoute: CyclesCycleIdStudyPackRoute,
}

const CyclesCycleIdRouteWithChildren = CyclesCycleIdRoute._addFileChildren(
  CyclesCycleIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaptureCycleIdRoute: CaptureCycleIdRoute,
  CyclesCycleIdRoute: CyclesCycleIdRouteWithChildren,
  CyclesNewRoute: CyclesNewRoute,
  ResultsCycleIdRoute: ResultsCycleIdRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SettingsChildrenChildIdRoute: SettingsChildrenChildIdRoute,
  SettingsChildrenNewRoute: SettingsChildrenNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
